# Generated by Django 5.2.1 on 2025-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=100)),
                ('descripcionCiudad', models.TextField()),
                ('imagenCiudad', models.ImageField(upload_to='images/')),
                ('precioTour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ofertaTour', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
